issuer: https://dex.hsp.hostedzonehere.com/

ingress:
  enabled: true
  className: "nginx"
  hosts: 
    - host: solgate.us-east-1-pspo-next.f10325bd5163481d.hsp.philips.com
      paths:
        - path: /
          pathType: ImplementationSpecific

resources:
  requests:
    memory: 128Mi
    cpu: 100m
  limits:
    memory: 128Mi
    cpu: 100m
